name: lumide_material_icons
description: "Material icons for Lumide"
version: 1.0.0
homepage: https://lumide.dev
repository: https://github.com/SoFluffyOS/lumide_material_icons

executables:
  lumide_material_icons: main

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lumide_api: ^0.7.0

dev_dependencies:
  test:
  lints: ^6.0.0
